# Generated by Django 3.2.12 on 2022-03-20 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=20, unique=True)),
                ('max_students', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=2)),
                ('last_name', models.CharField(max_length=20)),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, max_length=20)),
                ('student_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('student_school', models.ForeignKey(db_column='school_id', on_delete=django.db.models.deletion.CASCADE, to='core.school')),
            ],
        ),
    ]
